#include "tool/web/web_assets.hpp"

namespace mv::tool::web {
namespace {

constexpr std::string_view INDEX_HTML = R"MVWEB(<!doctype html>
<html lang="zh-CN">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1">
<title>MiracleVision 调试台</title>
<style>
:root{color-scheme:dark;--bg:#08111d;--panel:#101d2b;--line:#26394d;--text:#e7f0f8;--muted:#8fa5b9;--cyan:#38d9c5;--amber:#ffbd4a;--red:#ff657a}*{box-sizing:border-box}body{margin:0;background:radial-gradient(circle at top,#10263b,var(--bg) 45%);color:var(--text);font:14px system-ui,sans-serif}header{display:flex;align-items:center;justify-content:space-between;padding:18px 24px;border-bottom:1px solid var(--line)}h1{margin:0;font-size:21px}button,input,select{font:inherit}button{border:1px solid var(--line);border-radius:8px;background:#183047;color:var(--text);padding:9px 14px;cursor:pointer}button.primary{background:#087c71;border-color:var(--cyan)}button.warn{border-color:var(--amber)}button:disabled{opacity:.45;cursor:not-allowed}.wrap{max-width:1500px;margin:auto;padding:18px}.login{max-width:430px;margin:12vh auto;background:var(--panel);padding:26px;border:1px solid var(--line);border-radius:14px}.login input{width:100%;margin:14px 0;background:#07121e;color:var(--text);border:1px solid var(--line);border-radius:8px;padding:11px}.grid{display:grid;grid-template-columns:minmax(420px,1.15fr) minmax(440px,.85fr);gap:16px}.panel{background:rgba(16,29,43,.96);border:1px solid var(--line);border-radius:12px;padding:15px}.status{display:grid;grid-template-columns:repeat(4,1fr);gap:9px;margin-bottom:14px}.metric{background:#0a1724;border-radius:8px;padding:10px}.metric b{display:block;font-size:18px;margin-top:4px}.muted{color:var(--muted)}#preview{display:block;width:100%;min-height:260px;object-fit:contain;background:#02070c;border-radius:8px}.group{margin:0 0 14px;border:1px solid var(--line);border-radius:9px;padding:12px}.group h3{margin:0 0 10px}.field{display:grid;grid-template-columns:minmax(170px,1fr) 150px;gap:10px;align-items:center;margin:8px 0}.field label small{display:block;color:var(--muted)}.field input,.field select{width:100%;background:#081522;color:var(--text);border:1px solid var(--line);border-radius:7px;padding:7px}.changed input,.changed select{border-color:var(--amber)}.actions{position:sticky;bottom:0;display:flex;gap:8px;align-items:center;background:var(--panel);padding:12px 0 2px}.error{color:var(--red);white-space:pre-wrap}.ok{color:var(--cyan)}.hidden{display:none!important}@media(max-width:950px){.grid{grid-template-columns:1fr}.status{grid-template-columns:repeat(2,1fr)}}
</style>
</head>
<body>
<div id="login" class="login"><h1>MiracleVision 调试台</h1><p class="muted">输入视觉 PC 的 Web 调试密码。</p><input id="password" type="password" autocomplete="current-password" placeholder="密码"><button id="loginBtn" class="primary">连接</button><p id="loginError" class="error"></p></div>
<main id="app" class="hidden"><header><h1>MiracleVision 调试台</h1><div><span id="connection" class="muted">连接中</span> <button id="logout">退出</button></div></header><div class="wrap"><div class="status"><div class="metric"><span class="muted">图像帧</span><b id="sequence">--</b></div><div class="metric"><span class="muted">帧延迟</span><b id="age">--</b></div><div class="metric"><span class="muted">检测/候选</span><b id="detections">--</b></div><div class="metric"><span class="muted">检测耗时</span><b id="latency">--</b></div></div><div class="grid"><section class="panel"><img id="preview" alt="等待相机预览"><p id="previewInfo" class="muted"></p><h3>灯条诊断</h3><p id="lightStatus" class="muted">--</p></section><section class="panel"><div id="revision" class="muted"></div><div id="fields"></div><div class="actions"><button id="discard">放弃草稿</button><button id="restore" class="warn">恢复启动值</button><button id="apply" class="primary">统一应用</button><span id="message" class="muted"></span></div></section></div></div></main>
<script>
const $=id=>document.getElementById(id);sessionStorage.removeItem('mvWebToken');let password=sessionStorage.getItem('mvWebPassword')||'';let schema=[],startup=null,active=null,draft=null,revision=1,previewUrl='';
async function api(path,opt={}){const headers={...(opt.headers||{}),Authorization:`Bearer ${password}`};if(opt.body)headers['Content-Type']='application/json';const r=await fetch(path,{...opt,headers,cache:'no-store'});if(r.status===401){logout();throw Error('密码错误')};const text=await r.text();let data={};try{data=text?JSON.parse(text):{}}catch{data={message:text}}if(!r.ok)throw Error(data.message||`HTTP ${r.status}`);return data}
function get(obj,path){return path.split('.').reduce((v,k)=>v[k],obj)}function set(obj,path,value){const keys=path.split('.');let v=obj;keys.slice(0,-1).forEach(k=>v=v[k]);v[keys.at(-1)]=value}
function same(a,b){return JSON.stringify(a)===JSON.stringify(b)}function render(){const root=$('fields');root.innerHTML='';for(const group of [...new Set(schema.map(x=>x.group))]){const box=document.createElement('div');box.className='group';box.innerHTML=`<h3>${group}</h3>`;schema.filter(x=>x.group===group).forEach(item=>{const row=document.createElement('div');const changed=get(draft,item.path)!==get(active,item.path);row.className='field'+(changed?' changed':'');const label=document.createElement('label');label.innerHTML=`${item.label}<small>${item.description}${item.unit?' · '+item.unit:''}</small>`;let input;if(item.type==='enum'){input=document.createElement('select');item.values.forEach(v=>input.add(new Option(v,v)))}else if(item.type==='boolean'){input=document.createElement('select');input.add(new Option('启用','true'));input.add(new Option('禁用','false'))}else{input=document.createElement('input');input.type='number';if(item.min!==undefined)input.min=item.min;if(item.max!==undefined)input.max=item.max;input.step=item.step||'any'}input.value=String(get(draft,item.path));input.onchange=()=>{let value=input.value;if(item.type==='number')value=Number(value);if(item.type==='integer')value=Number.parseInt(value,10);if(item.type==='boolean')value=value==='true';set(draft,item.path,value);render()};row.append(label,input);box.append(row)});root.append(box)}$('apply').disabled=same(active,draft);$('discard').disabled=same(active,draft);$('revision').textContent=`当前配置 revision ${revision}`}
async function loadConfig(){const [s,c]=await Promise.all([api('/api/v1/frontend-schema'),api('/api/v1/frontend-config')]);schema=s.parameters;startup=c.startup;active=c.active;draft=structuredClone(active);revision=c.revision;render()}
async function statusLoop(){if(!password)return;try{const s=await api('/api/v1/status');$('connection').textContent='已连接';$('connection').className='ok';$('sequence').textContent=s.vision.has_frame?s.vision.sequence:'--';$('age').textContent=s.vision.has_frame?`${s.vision.frame_age_ms.toFixed(0)} ms`:'--';$('detections').textContent=s.vision.has_frame?`${s.vision.detections} / ${s.vision.candidates}`:'--';$('latency').textContent=s.vision.has_frame?`${s.vision.detector_ms.toFixed(2)} ms`:'--';$('lightStatus').textContent=s.vision.has_frame?`阈值 ${s.vision.lightbar_threshold}，轮廓 ${s.vision.lightbar_contours}，保留 ${s.vision.lightbar_kept}，耗时 ${s.vision.lightbar_ms.toFixed(2)} ms`:'等待图像';$('previewInfo').textContent=`预览帧 ${s.preview.sequence||'--'} · 覆盖 ${s.preview.overwritten_frames} · 编码错误 ${s.preview.encoding_errors}`;$('message').className=s.tuning.last_error?'error':'muted';$('message').textContent=s.tuning.pending?`revision ${s.tuning.target_revision} 等待下一帧生效`:s.tuning.last_error||'';if(s.tuning.revision!==revision&&!s.tuning.pending)await loadConfig()}catch(e){$('connection').textContent=e.message;$('connection').className='error'}setTimeout(statusLoop,500)}
async function previewLoop(){if(!password)return;try{const r=await fetch('/api/v1/preview.jpg',{headers:{Authorization:`Bearer ${password}`},cache:'no-store'});if(r.status===401){logout();return}if(r.ok){const blob=await r.blob();if(previewUrl)URL.revokeObjectURL(previewUrl);previewUrl=URL.createObjectURL(blob);$('preview').src=previewUrl}}catch{}setTimeout(previewLoop,125)}
async function login(){password=$('password').value.trim();if(!password)return;try{await api('/api/v1/status');sessionStorage.setItem('mvWebPassword',password);$('login').classList.add('hidden');$('app').classList.remove('hidden');await loadConfig();statusLoop();previewLoop()}catch(e){$('loginError').textContent=e.message}}
function logout(){password='';sessionStorage.removeItem('mvWebPassword');$('password').value='';$('app').classList.add('hidden');$('login').classList.remove('hidden')}
$('loginBtn').onclick=login;$('password').onkeydown=e=>{if(e.key==='Enter')login()};$('logout').onclick=logout;$('discard').onclick=()=>{draft=structuredClone(active);render()};$('restore').onclick=()=>{draft=structuredClone(startup);render()};$('apply').onclick=async()=>{try{$('apply').disabled=true;const r=await api('/api/v1/frontend-config',{method:'PUT',body:JSON.stringify({base_revision:revision,config:draft})});$('message').className='muted';$('message').textContent=`事务 ${r.request_id} 已提交，等待帧边界`}catch(e){$('message').textContent=e.message;$('message').className='error';render()}};
if(password){$('password').value=password;login()}
</script>
</body>
</html>)MVWEB";

}  // namespace

std::string_view IndexHtml() noexcept {
  return INDEX_HTML;
}

}  // namespace mv::tool::web
