find_package(Threads REQUIRED)
find_package(fmt REQUIRED)
find_package(spdlog REQUIRED)
find_package(yaml-cpp REQUIRED)
find_package(Eigen3 3.4 REQUIRED NO_MODULE)
find_package(OpenCV REQUIRED COMPONENTS core)
# Existing differentiable motion model uses Ceres Jet headers, not the detector/runtime.
find_package(Ceres 2.0 REQUIRED)
set(CMAKE_POSITION_INDEPENDENT_CODE ON)
add_subdirectory(src/core)
add_subdirectory(src/geometry)
add_library(mv-hal-gimbal INTERFACE)
target_include_directories(mv-hal-gimbal INTERFACE ${CMAKE_CURRENT_SOURCE_DIR}/src)
add_subdirectory(3rdparty/tinympc)
add_subdirectory(src/modules/prediction_model)
add_subdirectory(src/modules/gimbal_trajectory_planner)
add_subdirectory(src/modules/fire_control)
add_subdirectory(test/control)
